docker-build-all:
	docker buildx build --platform linux/amd64,linux/arm64 -t anvztor/geth:latest --push .

docker-build:
	docker buildx build --platform linux/amd64 -t anvztor/geth:latest --load .

docker-build-x:
	docker buildx build --platform linux/arm64 -t anvztor/geth:latest --load .