name: dogecoin-regtest

services:
  dogecoin-relayer-01:
    image: anvztor/dogecoin-relayer:latest
    container_name: dogecoin-relayer-01
    env_file:
      - ./data/node-01/.env
    environment:
      - RELAYER_PRIVATE_KEY=3ae009be18b897c016a05e79eae77adaff96f42bfc5c41aee696dd034bd52485
      - RELAYER_BLS_SK=0fd5fff3d663db00001552d7e9c4040af4a48eec6b6bd487b23946c763b85444
      - TSS_ENDPOINT=http://goat-network-tss-node1:8080
      - CONTRACT_TASK_MANAGER=0x6827D591faDa19A1274Df0Ab2608901AaaEA14C9
      - HTTP_PORT=8080
      - RPC_PORT=50051
      - LIBP2P_PORT=4001
    ports:
      - "8181:8080"
      - "4011:4001"
    volumes:
      - ./data/node-01/db:/app/data
      - ./data/node-01/p2p:/app/p2p
      - ./data/node-01/config.yaml:/app/config/config.yaml
    networks:
      goat_network:
        ipv4_address: 172.31.32.112

  dogecoin-relayer-02:
    image: anvztor/dogecoin-relayer:latest
    depends_on:
      dogecoin-relayer-01:
        condition: service_started
    container_name: dogecoin-relayer-02
    env_file:
      - ./data/node-02/.env
    environment:
      - LIBP2P_BOOT_NODES=/ip4/172.31.32.112/tcp/4001/p2p/12D3KooWEyrTn9ZD2Kidma4EKZ7ajaa7XDdje822WNZBRxpwQBYx
      - RELAYER_PRIVATE_KEY=cabee56de401798749faddaa98ae6b46eda2d152aca0c7ebd2c3d84fd39e3199
      - RELAYER_BLS_SK=5052000b478e7df866ecb7458fc4369f0fb912070f8c440de36a2bc7a60180fb
      - TSS_ENDPOINT=http://goat-network-tss-node2:8080
      - CONTRACT_TASK_MANAGER=0x6827D591faDa19A1274Df0Ab2608901AaaEA14C9
      - HTTP_PORT=8180
      - RPC_PORT=51051
      - LIBP2P_PORT=4101
    ports:
      - "8182:8080"
      - "4012:4001"
    volumes:
      - ./data/node-02/db:/app/data
      - ./data/node-02/p2p:/app/p2p
      - ./data/node-02/config.yaml:/app/config/config.yaml
    networks:
      goat_network:
        ipv4_address: 172.31.32.113

  dogecoin-relayer-03:
    image: anvztor/dogecoin-relayer:latest
    depends_on:
      dogecoin-relayer-01:
        condition: service_started
    container_name: dogecoin-relayer-03
    env_file:
      - ./data/node-03/.env
    environment:
      - LIBP2P_BOOT_NODES=/ip4/172.31.32.112/tcp/4001/p2p/12D3KooWEyrTn9ZD2Kidma4EKZ7ajaa7XDdje822WNZBRxpwQBYx
      - RELAYER_PRIVATE_KEY=8bda3b22eeeeff76de1b0d82a18235c1f1673a6b65e716e2d3fcbff56b8519de
      - RELAYER_BLS_SK=20adeb98d60d3edfcb8f07e9f51b39230a3c380fed4649b50c7a6b62228ccebd
      - TSS_ENDPOINT=http://goat-network-tss-node3:8080
      - CONTRACT_TASK_MANAGER=0x6827D591faDa19A1274Df0Ab2608901AaaEA14C9
      - HTTP_PORT=8280
      - RPC_PORT=52051
      - LIBP2P_PORT=4201
    ports:
      - "8183:8080"
      - "4013:4001"
    volumes:
      - ./data/node-03/db:/app/data
      - ./data/node-03/p2p:/app/p2p
      - ./data/node-03/config.yaml:/app/config/config.yaml
    networks:
      goat_network:
        ipv4_address: 172.31.32.114
        
networks:
  goat_network:
    external: true