name: goat-regtest

services:
  geth:
    image: anvztor/geth:latest
    container_name: goat-regtest-geth-node
    pull_policy: if_not_present
    stop_grace_period: 30s
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "geth attach --exec eth.blockNumber"]
      interval: 5s
      timeout: 5s
      retries: 5
    command:
      - --http
      - --http.api=eth,net,web3
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --syncmode=full
      - --nodiscover
    ports:
      - 8545:8545
      - 8551:8551
      - 30303:30303
    volumes:
      - ./data/geth:/root/.ethereum
    networks:
      - goat_network

  goat:
    image: anvztor/goat:latest
    container_name: goat-regtest-goat-node
    pull_policy: if_not_present
    stop_grace_period: 30s
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "goatd status"]
      interval: 5s
      timeout: 5s
      retries: 5
    command:
      - --home
      - /goat
      - --goat.geth
      - /geth/geth.ipc
      - --api.enable
      - --api.address=tcp://0.0.0.0:1317
    ports:
      - 9090:9090
      - 26657:26657
      - 26656:26656
      - 1317:1317
    volumes:
      - ./data/goat:/goat
      - ./data/geth:/geth
    depends_on:
      geth:
        condition: service_healthy
    networks:
      - goat_network

networks:
  goat_network:
    external: true