services:
  goat-network-tss-node1:
    image: anvztor/tss:dev
    container_name: goat-network-tss-node1
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8180/api/v1/evm/address?kdd=1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - SHARED_AES_KEY=3adafd7b6f7f722cb3d88ad5f6b59ff096facd412dfb7df130c9400f8c1559a5
    ports:
      - "8081:8180" # http port
      - "9091:9009" # p2p port
    volumes:
      - ./data/tss/node1/data:/app/data
      - ./data/tss/node1/config:/app/config
    networks:
      goat_network:
        ipv4_address: 172.31.32.91

  goat-network-tss-node2:
    image: anvztor/tss:dev
    container_name: goat-network-tss-node2
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8180/api/v1/evm/address?kdd=1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - SHARED_AES_KEY=daaa176a01c297855fb0055a4ba3771c73c554c8d4cd4c8ec14f1d59ffd8e0ba
    ports:
      - "8082:8180" # http port
      - "9092:9009" # p2p port
    volumes:
      - ./data/tss/node2/data:/app/data
      - ./data/tss/node2/config:/app/config
    networks:
      goat_network:
        ipv4_address: 172.31.32.92

  goat-network-tss-node3:
    image: anvztor/tss:dev
    container_name: goat-network-tss-node3
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8180/api/v1/evm/address?kdd=1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - SHARED_AES_KEY=33a6de2f05a899ab9b1efa61e0cbef624400ad388d364e1c7d598808c1963f6a
    ports:
      - "8083:8180" # http port
      - "9093:9009" # p2p port
    volumes:
      - ./data/tss/node3/data:/app/data
      - ./data/tss/node3/config:/app/config
    networks:
      goat_network:
        ipv4_address: 172.31.32.93

networks:
  goat_network:
    external: true