name: goat-regtest

services:
  bitcoin-core:
    image: ruimarinho/bitcoin-core:${VERSION:-latest}
    container_name: bitcoin-regtest
    volumes:
      - ./data/bitcoin:/home/bitcoin/.bitcoin
    ports:
      - 18443:18443
      - 18444:18444
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        bitcoind -regtest -datadir=/home/bitcoin/.bitcoin -daemon -regtest=1 -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0 -txindex=1 -reindex=1 -fallbackfee=0.01 -rpcuser=test -rpcpassword=test -discover=0 -server=1
        sleep 10

        # Load wallet
        bitcoin-wallet -regtest -wallet=demo create
        mkdir -p /home/bitcoin/.bitcoin/regtest/wallets/demo/
        cp /root/.bitcoin/regtest/wallets/demo/wallet.dat /home/bitcoin/.bitcoin/regtest/wallets/demo/wallet.dat
        cd /home/bitcoin/.bitcoin/regtest/wallets/
        chmod 777 -R demo/
        bitcoin-cli -regtest -rpcuser=test -rpcpassword=test loadwallet demo
        
        # Generate 199 blocks to get miner reward, execute only during initialization
        if [ $(bitcoin-cli -regtest -rpcuser=test -rpcpassword=test getblockcount) -le 199 ]; then
          bitcoin-cli -regtest -rpcuser=test -rpcpassword=test -generate 199
          bitcoin-cli -regtest -rpcuser=test -rpcpassword=test sendtoaddress bcrt1qksncyqxd4857fa8uadklcj56a5g45zmqvmzccq 100
          bitcoin-cli -regtest -rpcuser=test -rpcpassword=test -generate 1
        fi

        # Generate 1 block every 2 minutes by default, modify the interval as needed
        while true; do
          bitcoin-cli -regtest -rpcuser=test -rpcpassword=test -generate 1
          sleep 120
        done

        tail -f /dev/null
    networks:
      - goat_network

  electrs:
    image: vulpemventures/electrs:latest
    container_name: bitcoin-electrs
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        electrs -v --network regtest --daemon-dir /home/bitcoin/.bitcoin --daemon-rpc-addr bitcoin-regtest:18443 --daemon-auth test:test --http-addr 0.0.0.0:3002 --cookie-file /home/bitcoin/.bitcoin/.cookie --electrum-rpc-addr 0.0.0.0:60401 --cors '*'
    depends_on:
      - bitcoin-core
    ports:
      - "60401:60401"
      - "3002:3002"
    volumes:
      - ./data/bitcoin:/home/bitcoin/.bitcoin
      - ./data/electrs:/home/electrs/db
    networks:
      - goat_network

  mempool-frontend:
    environment:
      FRONTEND_HTTP_PORT: "8800"
      BACKEND_MAINNET_HTTP_HOST: "mempool-backend"
    image: mempool/frontend:latest
    container_name: mempool-frontend
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for mempool-db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - "8800:8800"
    depends_on:
      - mempool-backend
    networks:
      - goat_network

  mempool-backend:
    environment:
      MEMPOOL_BACKEND: "electrum"
      ELECTRUM_HOST: "electrs"
      ELECTRUM_PORT: "60401"
      ELECTRUM_TLS_ENABLED: "false"
      CORE_RPC_HOST: "bitcoin-regtest"
      CORE_RPC_PORT: "18443"
      CORE_RPC_USERNAME: "test"
      CORE_RPC_PASSWORD: "test"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "mempool-db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
      NETWORK: "regtest"
      # Enable address indexing
      # ADDRESS_INDEXING_ENABLED: "true"
      # INDEXING_INTERVAL_BLOCKS: "1"
      # INDEXING_INTERVAL_MS: "30000"
      # CLEAR_PROTECTION_ENABLED: "false"
      # POOLS_PARSING_ENABLED: "false"
    image: mempool/backend:latest
    container_name: mempool-backend
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for-it.sh mempool-db:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - ./data/mempool/cache:/backend/cache
    ports:
      - "8999:8999"
    depends_on:
      - mempool-db
      - electrs
    networks:
      - goat_network

  mempool-db:
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    image: mariadb:10.5.21
    container_name: mempool-db
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ./data/mempool/mysql:/var/lib/mysql
    networks:
      - goat_network

networks:
  goat_network:
    external: true
