services:
  dogecoin-node:
    extends:
      file: docker-compose-dogecoin.yml
      service: dogecoin-node

  dogecoin-miner:
    depends_on:
      - dogecoin-node
    extends:
      file: docker-compose-dogecoin.yml
      service: dogecoin-miner

  geth:
    depends_on:
      - dogecoin-node
    extends:
      file: docker-compose-geth.yml
      service: geth

  geth-prefund:
    depends_on:
      geth:
        condition: service_healthy
    extends:
      file: docker-compose-geth.yml
      service: geth-prefund

  deploy-contract:
    depends_on:
      geth:
        condition: service_healthy
      geth-prefund:
        condition: service_completed_successfully
    extends:
      file: docker-compose-geth.yml
      service: deploy-contract

  setup-contract:
    depends_on:
      deploy-contract:
        condition: service_completed_successfully
    extends:
      file: docker-compose-geth.yml
      service: setup-contract

  goat-network-tss-node1:
    extends:
      file: docker-compose-tss.yml
      service: goat-network-tss-node1

  goat-network-tss-node2:
    extends:
      file: docker-compose-tss.yml
      service: goat-network-tss-node2

  goat-network-tss-node3:
    extends:
      file: docker-compose-tss.yml
      service: goat-network-tss-node3

  dogecoin-relayer-01:
    depends_on:
      goat-network-tss-node1:
        condition: service_healthy
    extends:
      file: docker-compose-relayer.yml
      service: dogecoin-relayer-01

  dogecoin-relayer-02:
    depends_on:
      - dogecoin-relayer-01
    extends:
      file: docker-compose-relayer.yml
      service: dogecoin-relayer-02

  dogecoin-relayer-03:
    depends_on:
      - dogecoin-relayer-01
    extends:
      file: docker-compose-relayer.yml
      service: dogecoin-relayer-03

networks:
  goat_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.32.0/20
          gateway: 172.31.32.1