services:
  bitcoin-core:
    extends:
      file: docker-compose-bitcoin.yml
      service: bitcoin-core

  electrs:
    extends:
      file: docker-compose-bitcoin.yml
      service: electrs
    depends_on:
      - bitcoin-core

  mempool-db:
    extends:
      file: docker-compose-bitcoin.yml
      service: mempool-db

  mempool-backend:
    extends:
      file: docker-compose-bitcoin.yml
      service: mempool-backend
    depends_on:
      - mempool-db
      - electrs

  mempool-frontend:
    extends:
      file: docker-compose-bitcoin.yml
      service: mempool-frontend
    depends_on:
      - mempool-backend

  geth:
    extends:
      file: docker-compose-goat-geth.yml
      service: geth

  goat:
    depends_on:
      - bitcoin-core
      - geth
    extends:
      file: docker-compose-goat-geth.yml
      service: goat

  deploy-contract:
    depends_on:
      geth:
        condition: service_healthy  
    extends:
      file: docker-compose-goat-geth.yml
      service: deploy-contract

  goat-network-tss-node1:
    extends:
      file: docker-compose-tss.yml
      service: goat-network-tss-node1

  goat-network-tss-node2:
    extends:
      file: docker-compose-tss.yml
      service: goat-network-tss-node2

  goat-network-tss-node3:
    extends:
      file: docker-compose-tss.yml
      service: goat-network-tss-node3

  goat-relayer-1:
    depends_on:
      goat:
        condition: service_healthy
      goat-network-tss-node1:
        condition: service_healthy
    extends:
      file: docker-compose-relayer.yml
      service: goat-relayer-1

  goat-relayer-2:
    depends_on:
      - goat-relayer-1
    extends:
      file: docker-compose-relayer.yml
      service: goat-relayer-2

  goat-relayer-3:
    depends_on:
      - goat-relayer-1
    extends:
      file: docker-compose-relayer.yml
      service: goat-relayer-3

  engine-api-dev:
    extends:
      file: docker-compose-front.yml
      service: engine-api-dev

  engine-dev:
    extends:
      file: docker-compose-front.yml
      service: engine-dev

  unisat-server-proxy:
    extends:
      file: docker-compose-front.yml
      service: unisat-server-proxy

  mysql:
    extends:
      file: docker-compose-front.yml
      service: mysql

  goat-deploy-thegraph:
    extends:
      file: docker-compose-subgraph.yml
      service: goat-deploy-thegraph

  graph-node:
    extends:
      file: docker-compose-subgraph.yml
      service: graph-node

  ipfs:
    extends:
      file: docker-compose-subgraph.yml
      service: ipfs

  postgres:
    extends:
      file: docker-compose-subgraph.yml
      service: postgres

networks:
  goat_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.32.0/20
          gateway: 172.31.32.1