name: goat-regtest

services:
  goat-relayer-1:
    build: .
    image: anvztor/relayer:latest
    container_name: goat-relayer-1
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "50051:50051"
      - "4001:4001"
    volumes:
      - ./data/db:/app/db
    networks:
      goat_network:
        ipv4_address: 172.31.32.12

  goat-relayer-2:
    image: anvztor/relayer:latest
    depends_on:
      goat-relayer-1:
        condition: service_started
    container_name: goat-relayer-2
    env_file:
      - .env
    environment:
      - LIBP2P_BOOT_NODES=/ip4/172.31.32.12/tcp/4001/p2p/12D3KooWEyrTn9ZD2Kidma4EKZ7ajaa7XDdje822WNZBRxpwQBYx
      - RELAYER_PRIVATE_KEY=5e7f25d4b09963ec8821bd5ac8e1acef7a735e3d63c5179ce37d7b4550f83783
      - RELAYER_BLS_SK=44e7e168a66a0d90cdb7babc4c51df850166e57ecf9f2ad1897158ff5740d337
    ports:
      - "8180:8080"
      - "51051:50051"
      - "4101:4001"
    volumes:
      - ./data/db2:/app/db
    networks:
      goat_network:
        ipv4_address: 172.31.32.13

  goat-relayer-3:
    image: anvztor/relayer:latest
    depends_on:
      goat-relayer-1:
        condition: service_started
    container_name: goat-relayer-3
    env_file:
      - .env
    environment:
      - LIBP2P_BOOT_NODES=/ip4/172.31.32.12/tcp/4001/p2p/12D3KooWEyrTn9ZD2Kidma4EKZ7ajaa7XDdje822WNZBRxpwQBYx
      - RELAYER_PRIVATE_KEY=44329f0e3b20fab9bc5f161476ae3fa65355e3c92ac756109147048cc45a3afa
      - RELAYER_BLS_SK=72de1536b88cf34b5da0d1a77cef20d2c631cce7bacc86fee87716ce6ec575e4
    ports:
      - "8280:8080"
      - "52051:50051"
      - "4201:4001"
    volumes:
      - ./data/db3:/app/db
    networks:
      goat_network:
        ipv4_address: 172.31.32.14
        
networks:
  goat_network:
    external: true