name: dogecoin-regtest

services:
  geth:
    image: ethereum/client-go:stable
    container_name: goat-regtest-geth-node
    pull_policy: if_not_present
    stop_grace_period: 30s
    restart: unless-stopped
    healthcheck:
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
      test: ["CMD-SHELL", "geth attach --exec 'eth.blockNumber' http://127.0.0.1:8545 > /dev/null || exit 1"]
    command:
      - --dev
      - --http
      - --http.api=personal,eth,net,web3
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --dev.period=1
    ports:
      - 8545:8545
      - 8551:8551
      - 30303:30303
    volumes:
      - ./data/geth:/root/.ethereum
    networks:
      - goat_network

  deploy-contract:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: goat-regtest-deploy-contract
    restart: on-failure
    environment:
      - ADMIN_ADDR=0x29cF29d4b2CD6Db07f6db43243e8E43fE3DC468e
      - RELAYER_ADDR=0x7242C2F9692681526822FF325f31f807f851f0Bb                       
      - GOAT_BRIDGE_CONTRACT=0xBC10000000000000000000000000000000000003
      - BITCOIN_CONTRACT=0xbc10000000000000000000000000000000000005    
      - PRIVATE_KEY=0xe918dfc447c7c21100b1501ec5886f29e6537718589812326e0b9941b1812aa4
      - BSC_ETHERSCAN_API_KEY=1
    volumes:
      - ./data/deploy-contract:/app
    working_dir: /app
    entrypoint: ["/bin/sh", "-c"]
    command: 
      - |
        cd /app
        forge install
        forge script script/Deploy.s.sol --rpc-url http://geth:8545 --broadcast --legacy
    depends_on:
      geth:
        condition: service_healthy
      geth-prefund:
        condition: service_completed_successfully
    networks:
      - goat_network

  setup-contract:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: goat-regtest-setup-contract
    restart: on-failure
    environment:
      - ADMIN_ADDR=0x29cF29d4b2CD6Db07f6db43243e8E43fE3DC468e
      - ENTRY_POINT=0xc3fC084D2e1C35Eb3Bf3CB7c342fF51636a2dDcE
      - TSS_SIGNER=0xD464FDf2320850a855B4b8c3420bcDE95f642FB8
      - PROPOSER_1=0xE07dc2f6112E5B38237cb9620eA0075eF25e5E79
      - PROPOSER_2=0x4E6588f5eb6D328ABB46df71C74D7031cC962C85
      - PROPOSER_3=0xe0a189c72078AB9A4B0ebfcd3eEf46153392a152
      - PRIVATE_KEY=0xe918dfc447c7c21100b1501ec5886f29e6537718589812326e0b9941b1812aa4
    volumes:
      - ./data/deploy-contract:/app
    working_dir: /app
    entrypoint: ["/bin/sh", "-c"]
    command: 
      - |
        cd /app
        forge install
        forge script script/EntryPointInit.sol --rpc-url http://geth:8545 --broadcast
    depends_on:
      deploy-contract:
        condition: service_completed_successfully
    networks:
      - goat_network

  geth-prefund:
    image: ethereum/client-go:stable
    container_name: goat-regtest-geth-prefund
    restart: "no"
    depends_on:
      geth:
        condition: service_healthy
    entrypoint: ["geth", "attach"]
    command: ["--exec", "eth.sendTransaction({from: eth.accounts[0], to: \"0x29cF29d4b2CD6Db07f6db43243e8E43fE3DC468e\", value: \"0x0DE0B6B3A7640000\"})", "http://geth:8545"]
    networks:
      - goat_network

networks:
  goat_network:
    external: true
