name: dogecoin-regtest

services:
  dogecoin-relayer-01:
    image: anvztor/dogecoin-relayer:latest
    container_name: dogecoin-relayer-01
    env_file:
      - ./data/relayer/node1/.env
    environment:
      - PROPOSER_PRIVATE_KEY=3ae009be18b897c016a05e79eae77adaff96f42bfc5c41aee696dd034bd52485
    ports:
      - "8181:8080"
      - "4011:4001"
    volumes:
      - ./data/relayer/node1/db:/app/data
      - ./data/relayer/node1/p2p:/app/p2p
      - ./data/relayer/node1/config.yaml:/app/config/config.yaml
    networks:
      goat_network:
        ipv4_address: 172.31.32.112

  dogecoin-relayer-02:
    image: anvztor/dogecoin-relayer:latest
    depends_on:
      dogecoin-relayer-01:
        condition: service_started
    container_name: dogecoin-relayer-02
    env_file:
      - ./data/relayer/node2/.env
    environment:
      - LIBP2P_BOOT_NODES=/ip4/172.31.32.112/tcp/4001/p2p/12D3KooWEyrTn9ZD2Kidma4EKZ7ajaa7XDdje822WNZBRxpwQBYx
      - PROPOSER_PRIVATE_KEY=cabee56de401798749faddaa98ae6b46eda2d152aca0c7ebd2c3d84fd39e3199
    ports:
      - "8182:8080"
      - "4012:4001"
    volumes:
      - ./data/relayer/node2/db:/app/data
      - ./data/relayer/node2/p2p:/app/p2p
      - ./data/relayer/node2/config.yaml:/app/config/config.yaml
    networks:
      goat_network:
        ipv4_address: 172.31.32.113

  dogecoin-relayer-03:
    image: anvztor/dogecoin-relayer:latest
    depends_on:
      dogecoin-relayer-01:
        condition: service_started
    container_name: dogecoin-relayer-03
    env_file:
      - ./data/relayer/node3/.env
    environment:
      - LIBP2P_BOOT_NODES=/ip4/172.31.32.112/tcp/4001/p2p/12D3KooWEyrTn9ZD2Kidma4EKZ7ajaa7XDdje822WNZBRxpwQBYx
      - PROPOSER_PRIVATE_KEY=8bda3b22eeeeff76de1b0d82a18235c1f1673a6b65e716e2d3fcbff56b8519de
    ports:
      - "8183:8080"
      - "4013:4001"
    volumes:
      - ./data/relayer/node3/db:/app/data
      - ./data/relayer/node3/p2p:/app/p2p
      - ./data/relayer/node3/config.yaml:/app/config/config.yaml
    networks:
      goat_network:
        ipv4_address: 172.31.32.114
        
networks:
  goat_network:
    external: true