name: goat-regtest

services:
  goat-relayer-1:
    build: .
    image: anvztor/relayer:latest
    container_name: goat-relayer-1
    env_file:
      - .env
    environment:
      - RELAYER_PRIVATE_KEY=3ae009be18b897c016a05e79eae77adaff96f42bfc5c41aee696dd034bd52485
      - RELAYER_BLS_SK=0fd5fff3d663db00001552d7e9c4040af4a48eec6b6bd487b23946c763b85444
      - HTTP_PORT=8080
      - RPC_PORT=50051
      - LIBP2P_PORT=4001
    ports:
      - "8080:8080"
      - "50051:50051"
      - "4001:4001"
    volumes:
      - ./data/db:/app/db
    networks:
      goat_network:
        ipv4_address: 172.31.32.12

  goat-relayer-2:
    image: anvztor/relayer:latest
    depends_on:
      goat-relayer-1:
        condition: service_started
    container_name: goat-relayer-2
    env_file:
      - .env
    environment:
      - LIBP2P_BOOT_NODES=/ip4/172.31.32.12/tcp/4001/p2p/12D3KooWEyrTn9ZD2Kidma4EKZ7ajaa7XDdje822WNZBRxpwQBYx
      - RELAYER_PRIVATE_KEY=cabee56de401798749faddaa98ae6b46eda2d152aca0c7ebd2c3d84fd39e3199
      - RELAYER_BLS_SK=5052000b478e7df866ecb7458fc4369f0fb912070f8c440de36a2bc7a60180fb
      - HTTP_PORT=8180
      - RPC_PORT=51051
      - LIBP2P_PORT=4101
    ports:
      - "8180:8180"
      - "51051:51051"
      - "4101:4101"
    volumes:
      - ./data/db2:/app/db
    networks:
      goat_network:
        ipv4_address: 172.31.32.13

  goat-relayer-3:
    image: anvztor/relayer:latest
    depends_on:
      goat-relayer-1:
        condition: service_started
    container_name: goat-relayer-3
    env_file:
      - .env
    environment:
      - LIBP2P_BOOT_NODES=/ip4/172.31.32.12/tcp/4001/p2p/12D3KooWEyrTn9ZD2Kidma4EKZ7ajaa7XDdje822WNZBRxpwQBYx
      - RELAYER_PRIVATE_KEY=8bda3b22eeeeff76de1b0d82a18235c1f1673a6b65e716e2d3fcbff56b8519de
      - RELAYER_BLS_SK=20adeb98d60d3edfcb8f07e9f51b39230a3c380fed4649b50c7a6b62228ccebd
      - HTTP_PORT=8280
      - RPC_PORT=52051
      - LIBP2P_PORT=4201
    ports:
      - "8280:8280"
      - "52051:52051"
      - "4201:4201"
    volumes:
      - ./data/db3:/app/db
    networks:
      goat_network:
        ipv4_address: 172.31.32.14
        
networks:
  goat_network:
    external: true