nodeId: node-1
peerId: "12D3KooWFtfTU3LBnNaNpPSyWE3UDXw1NFyYZccMKtLYVqf9XmYH"
address: "0xffe89dfe907a8dfdafdb48dffbae86445b02a93e"
logLevel: debug
http:
  port: 8180
p2p:
  listenAddr: /ip4/0.0.0.0/tcp/9009
  externalAddr: /ip4/172.31.32.91/tcp/9009
  bootstrapPeers:
    # - /ip4/172.31.32.91/tcp/9009/p2p/12D3KooWFtfTU3LBnNaNpPSyWE3UDXw1NFyYZccMKtLYVqf9XmYH
    - /ip4/172.31.32.92/tcp/9009/p2p/12D3KooWQk9bNDztJu3Qy1Sy6SJpQXpJ4VbLxdXY9LHwWW6BA7zb
    - /ip4/172.31.32.93/tcp/9009/p2p/12D3KooWT3ehGxkyzA2vhqfgjvNC3hUeQRQgvhYE5KVZftUjBKRg
  enableMDNS: false
  listenWaitSeconds: 0
  connectionWaitSeconds: 30
tss:
  oldThreshold: 1
  threshold: 1
  totalParties: 3
  keyId: "1"
  newKeyId: "2"
  keysDir: /app/data/keys
  chainType: EVM
  timeout: 300s
  localPartyDelay: 10s
  participants:
    - peerId: "12D3KooWFtfTU3LBnNaNpPSyWE3UDXw1NFyYZccMKtLYVqf9XmYH"
      key: 1
      moniker: node-1
    - peerId: "12D3KooWQk9bNDztJu3Qy1Sy6SJpQXpJ4VbLxdXY9LHwWW6BA7zb"
      key: 2
      moniker: node-2
    - peerId: "12D3KooWT3ehGxkyzA2vhqfgjvNC3hUeQRQgvhYE5KVZftUjBKRg"
      key: 3
      moniker: node-3